version: '2'
services:
  autochangeset-app:
    image: autochangeset
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://autochangeset-postgresql:5432/AutoChangeSet
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8083:8083
  autochangeset-postgresql:
    extends:
      file: postgresql.yml
      service: autochangeset-postgresql
